name: Build one

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        type: string
        required: false
        default: main
      enable_v8:
        description: Enable V8
        type: boolean
        required: false
        default: false
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false
      target_os:
        description: Target OS (android|ios|linux|mac|win)
        type: string
        required: true
        default: android
      target_cpu:
        description: Target CPU (arm|arm64|x64|x86)
        type: string
        required: true
        default: arm64
      target_environment:
        description: Target environment (device|catalyst|simulator)
        type: string
        required: false
        default: ''

permissions:
  contents: read
  actions: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ inputs.branch }}
      enable_v8: ${{ inputs.enable_v8 }}
      is_debug: ${{ inputs.is_debug }}
      target_os: ${{ inputs.target_os }}
      target_cpu: ${{ inputs.target_cpu }}
      target_environment: ${{ inputs.target_environment }}
    secrets: inherit
